theme: jekyll-theme-cayman
title: Chike Okwudiafor
description: Data Scientist/Analyst
logo: https://media-exp1.licdn.com/dms/image/D4E35AQEvDDPIgBnVXQ/profile-framedphoto-shrink_400_400/0/1635187959173?e=1638475200&v=beta&t=b_ZVF8Iw4EmoY8oRbzfdhHqiZJnva9MLi-Jyg8pOoTQ
show_downloads: false
